### ISSUE TITLE
EFP name handling from groundfish trip attributes

### ISSUE THREAD

**Issue by galuardi** [noaa-garfo/discaRd#20]
The EFP names are managed in the FMP_MGMT schema, under RESEARCH_PERMIT_GROUP.  Naming conventions vary over the years, and only some are relevant to stratification to groundfish discards.

For example, "EM2" and "Audit Model 2019" are the same thing.  As is "Audit Model 2020".

This creates a tedious programming nightmare...

**Comment by galuardi** [comment]
refactor 

```sql

select *
from fmp_mgmt.research_group_vessel_roster
/

select *
from fmp_mgmt.research_permit_group
```

for better EFP designation

**Comment by danlinden** [comment]
The only EFPs used for stratification are related to EM:
1) EM1 or PARTIAL EM
2) EM2 or AUDIT
3) MREM

These have been identified as an "EM" column in STG_TRIP_ATTR with NULL for non-EM trips.
